name: Python application


on:
  push:
    branches:
      - "**" # This will match any branch
  pull_request:
    branches:
      - "**" # This will match any branch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        # python -m venv env
        # source env/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --ignore=E221 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E221 --statistics

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run the OpenSearch docker image
      run: |
        python src/db_scripts/run_opensearch_container.py
        python src/db_scripts/create_index_script.py
        python src/db_scripts/update_index_script.py

    - name: Setup the web-front docker image
      run: |
        docker build -t financial_insights .
        docker run -p 8000:8000 financial_insights

    - name: Test with pytest
      run: |
        pytest test/src/test_db_scripts.py
        # pytest test/src/test_llm_request_parser.py
        # pytest test/src/test_llm_request_parser.py
        # pytest test/src/test_web_app.py
